name = "Euonymus Euonymus Hamiltonianus"

[[fatty_acids]]
data = { tag123 = 33.6, mag2 = 0.0, dag1223 = 47.3 }
description = "16:0"
formula = "C16H32O2"
label = "P"

[[fatty_acids]]
data = { tag123 = 2.0, mag2 = 2.1, dag1223 = 1.7 }
description = "16:1"
formula = "C16H30O2"
label = "H"

[[fatty_acids]]
data = { tag123 = 2.5, mag2 = 0.3, dag1223 = 3.7 }
description = "18:0"
formula = "C18H36O2"
label = "St"

[[fatty_acids]]
data = { tag123 = 16.4, mag2 = 15.0, dag1223 = 17.9 }
description = "18:1"
formula = "C18H34O2"
label = "O"

[[fatty_acids]]
data = { tag123 = 44.0, mag2 = 79.8, dag1223 = 28.4 }
description = "18:2"
formula = "C18H32O2"
label = "L"

[[fatty_acids]]
data = { tag123 = 1.5, mag2 = 2.8, dag1223 = 1.0 }
description = "18:3"
formula = "C18H30O2"
label = "Ln"
