name = "Euonymus Pseudovyenomus Pauciflorus"

[[fatty_acids]]
data = { tag123 = 26.7, mag2 = 0.5, dag1223 = 36.8 }
description = "16:0"
formula = "C16H32O2"
label = "P"

[[fatty_acids]]
data = { tag123 = 1.0, mag2 = 0.0, dag1223 = 1.3 }
description = "16:1"
formula = "C16H30O2"
label = "H"

[[fatty_acids]]
data = { tag123 = 5.4, mag2 = 0.0, dag1223 = 8.7 }
description = "18:0"
formula = "C18H36O2"
label = "St"

[[fatty_acids]]
data = { tag123 = 39.4, mag2 = 43.6, dag1223 = 38.7 }
description = "18:1"
formula = "C18H34O2"
label = "O"

[[fatty_acids]]
data = { tag123 = 26.5, mag2 = 54.0, dag1223 = 13.8 }
description = "18:2"
formula = "C18H32O2"
label = "L"

[[fatty_acids]]
data = { tag123 = 1.1, mag2 = 1.9, dag1223 = 0.7 }
description = "18:3"
formula = "C18H30O2"
label = "Ln"
