name = "Euonymus Euonymus Bungeanus"

[[fatty_acids]]
data = { tag123 = 28.1, mag2 = 0.0, dag1223 = 40.0 }
description = "16:0"
formula = "C16H32O2"
label = "P"

[[fatty_acids]]
data = { tag123 = 10.2, mag2 = 0.2, dag1223 = 14.0 }
description = "16:1"
formula = "C16H30O2"
label = "H"

[[fatty_acids]]
data = { tag123 = 1.5, mag2 = 0.0, dag1223 = 2.4 }
description = "18:0"
formula = "C18H36O2"
label = "St"

[[fatty_acids]]
data = { tag123 = 17.2, mag2 = 11.2, dag1223 = 21.0 }
description = "18:1"
formula = "C18H34O2"
label = "O"

[[fatty_acids]]
data = { tag123 = 41.7, mag2 = 86.4, dag1223 = 21.5 }
description = "18:2"
formula = "C18H32O2"
label = "L"

[[fatty_acids]]
data = { tag123 = 1.3, mag2 = 2.1, dag1223 = 1.0 }
description = "18:3"
formula = "C18H30O2"
label = "Ln"
