name = "Euonymus Melanocarya Alatus"

[[fatty_acids]]
data = { tag123 = 24.6, mag2 = 0.5, dag1223 = 34.1 }
description = "16:0"
formula = "C16H32O2"
label = "P"

[[fatty_acids]]
data = { tag123 = 0.5, mag2 = 0.4, dag1223 = 0.4 }
description = "16:1"
formula = "C16H30O2"
label = "H"

[[fatty_acids]]
data = { tag123 = 2.2, mag2 = 0.1, dag1223 = 3.3 }
description = "18:0"
formula = "C18H36O2"
label = "St"

[[fatty_acids]]
data = { tag123 = 23.5, mag2 = 18.4, dag1223 = 26.9 }
description = "18:1"
formula = "C18H34O2"
label = "O"

[[fatty_acids]]
data = { tag123 = 46.4, mag2 = 76.7, dag1223 = 33.0 }
description = "18:2"
formula = "C18H32O2"
label = "L"

[[fatty_acids]]
data = { tag123 = 2.8, mag2 = 3.9, dag1223 = 2.3 }
description = "18:3"
formula = "C18H30O2"
label = "Ln"
