name = "Euonymus Euonymus Sieboldianus"

[[fatty_acids]]
data = { tag123 = 20.0, mag2 = 0.1, dag1223 = 28.2 }
description = "16:0"
formula = "C16H32O2"
label = "P"

[[fatty_acids]]
data = { tag123 = 13.6, mag2 = 7.0, dag1223 = 15.6 }
description = "16:1"
formula = "C16H30O2"
label = "H"

[[fatty_acids]]
data = { tag123 = 2.1, mag2 = 0.0, dag1223 = 3.3 }
description = "18:0"
formula = "C18H36O2"
label = "St"

[[fatty_acids]]
data = { tag123 = 25.5, mag2 = 15.6, dag1223 = 31.5 }
description = "18:1"
formula = "C18H34O2"
label = "O"

[[fatty_acids]]
data = { tag123 = 37.8, mag2 = 75.4, dag1223 = 20.8 }
description = "18:2"
formula = "C18H32O2"
label = "L"

[[fatty_acids]]
data = { tag123 = 1.0, mag2 = 2.0, dag1223 = 0.6 }
description = "18:3"
formula = "C18H30O2"
label = "Ln"
