name = "Euonymus Euonymus Semiexsertus"

[[fatty_acids]]
data = { tag123 = 28.8, mag2 = 0.1, dag1223 = 40.2 }
description = "16:0"
formula = "C16H32O2"
label = "P"

[[fatty_acids]]
data = { tag123 = 0.6, mag2 = 0.2, dag1223 = 0.9 }
description = "16:1"
formula = "C16H30O2"
label = "H"

[[fatty_acids]]
data = { tag123 = 1.6, mag2 = 0.0, dag1223 = 2.5 }
description = "18:0"
formula = "C18H36O2"
label = "St"

[[fatty_acids]]
data = { tag123 = 16.6, mag2 = 7.3, dag1223 = 21.8 }
description = "18:1"
formula = "C18H34O2"
label = "O"

[[fatty_acids]]
data = { tag123 = 51.3, mag2 = 90.5, dag1223 = 33.9 }
description = "18:2"
formula = "C18H32O2"
label = "L"

[[fatty_acids]]
data = { tag123 = 1.2, mag2 = 1.9, dag1223 = 0.8 }
description = "18:3"
formula = "C18H30O2"
label = "Ln"
