name = "Euonymus Euonymus Phellomanus"

[[fatty_acids]]
data = { tag123 = 31.9, mag2 = 0.4, dag1223 = 44.7 }
description = "16:0"
formula = "C16H32O2"
label = "P"

[[fatty_acids]]
data = { tag123 = 1.3, mag2 = 0.0, dag1223 = 1.9 }
description = "16:1"
formula = "C16H30O2"
label = "H"

[[fatty_acids]]
data = { tag123 = 5.3, mag2 = 0.0, dag1223 = 8.8 }
description = "18:0"
formula = "C18H36O2"
label = "St"

[[fatty_acids]]
data = { tag123 = 18.3, mag2 = 10.8, dag1223 = 22.6 }
description = "18:1"
formula = "C18H34O2"
label = "O"

[[fatty_acids]]
data = { tag123 = 41.3, mag2 = 86.6, dag1223 = 20.5 }
description = "18:2"
formula = "C18H32O2"
label = "L"

[[fatty_acids]]
data = { tag123 = 1.8, mag2 = 2.1, dag1223 = 1.5 }
description = "18:3"
formula = "C18H30O2"
label = "Ln"
