name = "Euonymus Melanocarya Sacrosantcus"

[[fatty_acids]]
data = { tag123 = 22.3, mag2 = 0.5, dag1223 = 30.4 }
description = "16:0"
formula = "C16H32O2"
label = "P"

[[fatty_acids]]
data = { tag123 = 0.1, mag2 = 0.1, dag1223 = 1.4 }
description = "16:1"
formula = "C16H30O2"
label = "H"

[[fatty_acids]]
data = { tag123 = 2.0, mag2 = 0.3, dag1223 = 2.8 }
description = "18:0"
formula = "C18H36O2"
label = "St"

[[fatty_acids]]
data = { tag123 = 28.1, mag2 = 16.8, dag1223 = 34.3 }
description = "18:1"
formula = "C18H34O2"
label = "O"

[[fatty_acids]]
data = { tag123 = 44.6, mag2 = 77.5, dag1223 = 29.1 }
description = "18:2"
formula = "C18H32O2"
label = "L"

[[fatty_acids]]
data = { tag123 = 2.9, mag2 = 4.9, dag1223 = 2.0 }
description = "18:3"
formula = "C18H30O2"
label = "Ln"
