# Euonymus Euonymus Bungeanus

[[euonymus.euonymus.bungeanus]]
key = "P"
name = "Palmitic"
type = "S"
value = { sn123 = 28.1, sn2 = 0.0, sn13 = 40.0 }

[[euonymus.euonymus.bungeanus]]
key = "St"
name = "Stearic"
type = "S"
value = { sn123 = 1.5, sn2 = 0.0, sn13 = 2.4 }

[[euonymus.euonymus.bungeanus]]
key = "H"
name = "Hexadecenoic"
type = "U"
value = { sn123 = 10.2, sn2 = 0.2, sn13 = 14.0 }

[[euonymus.euonymus.bungeanus]]
key = "O"
name = "Octadecenoic"
type = "U"
value = { sn123 = 17.2, sn2 = 11.2, sn13 = 21.0 }

[[euonymus.euonymus.bungeanus]]
key = "L"
name = "Linoleic"
type = "U"
value = { sn123 = 41.7, sn2 = 86.4, sn13 = 21.5 }

[[euonymus.euonymus.bungeanus]]
key = "Ln"
name = "Linolenic"
type = "U"
value = { sn123 = 1.3, sn2 = 2.1, sn13 = 1.0 }

# Euonymus Euonymus Europaeus

[[euonymus.euonymus.europaeus]]
key = "P"
value = { sn123 = 23.2, sn2 = 0.0, sn13 = 28.6 }

[[euonymus.euonymus.europaeus]]
key = "St"
value = { sn123 = 1.5, sn2 = 0.0, sn13 = 2.8 }

[[euonymus.euonymus.europaeus]]
key = "H"
value = { sn123 = 6.8, sn2 = 2.7, sn13 = 6.9 }

[[euonymus.euonymus.europaeus]]
key = "O"
value = { sn123 = 20.5, sn2 = 12.5, sn13 = 26.8 }

[[euonymus.euonymus.europaeus]]
key = "L"
value = { sn123 = 45.6, sn2 = 81.1, sn13 = 32.8 }

[[euonymus.euonymus.europaeus]]
key = "Ln"
value = { sn123 = 2.5, sn2 = 3.7, sn13 = 2.1 }

# Euonymus Euonymus Hamiltonianus

[[euonymus.euonymus.hamiltonianus]]
key = "P"
value = { sn123 = 33.6, sn2 = 0.0, sn13 = 47.3 }

[[euonymus.euonymus.hamiltonianus]]
key = "St"
value = { sn123 = 2.5, sn2 = 0.3, sn13 = 3.7 }

[[euonymus.euonymus.hamiltonianus]]
key = "H"
value = { sn123 = 2.0, sn2 = 2.1, sn13 = 1.7 }

[[euonymus.euonymus.hamiltonianus]]
key = "O"
value = { sn123 = 16.4, sn2 = 15.0, sn13 = 17.9 }

[[euonymus.euonymus.hamiltonianus]]
key = "L"
value = { sn123 = 44.0, sn2 = 79.8, sn13 = 28.4 }

[[euonymus.euonymus.hamiltonianus]]
key = "Ln"
value = { sn123 = 1.5, sn2 = 2.8, sn13 = 1.0 }

# Euonymus Euonymus Phellomanus

[[euonymus.euonymus.phellomanus]]
key = "P"
value = { sn123 = 31.9, sn2 = 0.4, sn13 = 44.7 }

[[euonymus.euonymus.phellomanus]]
key = "St"
value = { sn123 = 5.3, sn2 = 0.0, sn13 = 8.8 }

[[euonymus.euonymus.phellomanus]]
key = "H"
value = { sn123 = 1.3, sn2 = 0.0, sn13 = 1.9 }

[[euonymus.euonymus.phellomanus]]
key = "O"
value = { sn123 = 18.3, sn2 = 10.8, sn13 = 22.6 }

[[euonymus.euonymus.phellomanus]]
key = "L"
value = { sn123 = 41.3, sn2 = 86.6, sn13 = 20.5 }

[[euonymus.euonymus.phellomanus]]
key = "Ln"
value = { sn123 = 1.8, sn2 = 2.1, sn13 = 1.5 }

# Euonymus Euonymus Semiexsertus

[[euonymus.euonymus.semiexsertus]]
key = "P"
value = { sn123 = 28.8, sn2 = 0.1, sn13 = 40.2 }

[[euonymus.euonymus.semiexsertus]]
key = "St"
value = { sn123 = 1.6, sn2 = 0.0, sn13 = 2.5 }

[[euonymus.euonymus.semiexsertus]]
key = "H"
value = { sn123 = 0.6, sn2 = 0.2, sn13 = 0.9 }

[[euonymus.euonymus.semiexsertus]]
key = "O"
value = { sn123 = 16.6, sn2 = 7.3, sn13 = 21.8 }

[[euonymus.euonymus.semiexsertus]]
key = "L"
value = { sn123 = 51.3, sn2 = 90.5, sn13 = 33.9 }

[[euonymus.euonymus.semiexsertus]]
key = "Ln"
value = { sn123 = 1.2, sn2 = 1.9, sn13 = 0.8 }

# Euonymus Euonymus Sieboldianus

[[euonymus.euonymus.sieboldianus]]
key = "P"
value = { sn123 = 20.0, sn2 = 0.1, sn13 = 28.2 }

[[euonymus.euonymus.sieboldianus]]
key = "St"
value = { sn123 = 2.1, sn2 = 0.0, sn13 = 3.3 }

[[euonymus.euonymus.sieboldianus]]
key = "H"
value = { sn123 = 13.6, sn2 = 7.0, sn13 = 15.6 }

[[euonymus.euonymus.sieboldianus]]
key = "O"
value = { sn123 = 25.5, sn2 = 15.6, sn13 = 31.5 }

[[euonymus.euonymus.sieboldianus]]
key = "L"
value = { sn123 = 37.8, sn2 = 75.4, sn13 = 20.8 }

[[euonymus.euonymus.sieboldianus]]
key = "Ln"
value = { sn123 = 1.0, sn2 = 2.0, sn13 = 0.6 }

# Euonymus Melanocarya Alatus

[[euonymus.melanocarya.alatus]]
key = "P"
value = { sn123 = 24.6, sn2 = 0.5, sn13 = 34.1 }

[[euonymus.melanocarya.alatus]]
key = "St"
value = { sn123 = 2.2, sn2 = 0.1, sn13 = 3.3 }

[[euonymus.melanocarya.alatus]]
key = "H"
value = { sn123 = 0.5, sn2 = 0.4, sn13 = 0.4 }

[[euonymus.melanocarya.alatus]]
key = "O"
value = { sn123 = 23.5, sn2 = 18.4, sn13 = 26.9 }

[[euonymus.melanocarya.alatus]]
key = "L"
value = { sn123 = 46.4, sn2 = 76.7, sn13 = 33.0 }

[[euonymus.melanocarya.alatus]]
key = "Ln"
value = { sn123 = 2.8, sn2 = 3.9, sn13 = 2.3 }

# Euonymus Melanocarya Sacrosantcus

[[euonymus.melanocarya.sacrosantcus]]
key = "P"
value = { sn123 = 22.3, sn2 = 0.5, sn13 = 30.4 }

[[euonymus.melanocarya.sacrosantcus]]
key = "St"
value = { sn123 = 2.0, sn2 = 0.3, sn13 = 2.8 }

[[euonymus.melanocarya.sacrosantcus]]
key = "H"
value = { sn123 = 0.1, sn2 = 0.1, sn13 = 1.4 }

[[euonymus.melanocarya.sacrosantcus]]
key = "O"
value = { sn123 = 28.1, sn2 = 16.8, sn13 = 34.3 }

[[euonymus.melanocarya.sacrosantcus]]
key = "L"
value = { sn123 = 44.6, sn2 = 77.5, sn13 = 29.1 }

[[euonymus.melanocarya.sacrosantcus]]
key = "Ln"
value = { sn123 = 2.9, sn2 = 4.9, sn13 = 2.0 }

# Euonymus Pseudovyenomus Pauciflorus

[[euonymus.pseudovyenomus.pauciflorus]]
key = "P"
value = { sn123 = 26.7, sn2 = 0.5, sn13 = 36.8 }

[[euonymus.pseudovyenomus.pauciflorus]]
key = "St"
value = { sn123 = 5.4, sn2 = 0.0, sn13 = 8.7 }

[[euonymus.pseudovyenomus.pauciflorus]]
key = "H"
value = { sn123 = 1.0, sn2 = 0.0, sn13 = 1.3 }

[[euonymus.pseudovyenomus.pauciflorus]]
key = "O"
value = { sn123 = 39.4, sn2 = 43.6, sn13 = 38.7 }

[[euonymus.pseudovyenomus.pauciflorus]]
key = "L"
value = { sn123 = 26.5, sn2 = 54.0, sn13 = 13.8 }

[[euonymus.pseudovyenomus.pauciflorus]]
key = "Ln"
value = { sn123 = 1.1, sn2 = 1.9, sn13 = 0.7 }

# Kalonymus Latifolius

[[kalonymus.latifolius]]
key = "P"
value = { sn123 = 19.1, sn2 = 0.2, sn13 = 27.1 }

[[kalonymus.latifolius]]
key = "St"
value = { sn123 = 2.0, sn2 = 0.0, sn13 = 3.1 }

[[kalonymus.latifolius]]
key = "H"
value = { sn123 = 1.4, sn2 = 1.3, sn13 = 1.4 }

[[kalonymus.latifolius]]
key = "O"
value = { sn123 = 56.5, sn2 = 63.2, sn13 = 54.2 }

[[kalonymus.latifolius]]
key = "L"
value = { sn123 = 18.4, sn2 = 30.7, sn13 = 12.6 }

[[kalonymus.latifolius]]
key = "Ln"
value = { sn123 = 2.6, sn2 = 4.6, sn13 = 1.7 }

# Kalonymus Macropterus

[[kalonymus.macropterus]]
key = "P"
value = { sn123 = 44.2, sn2 = 0.2, sn13 = 62.0 }

[[kalonymus.macropterus]]
key = "St"
value = { sn123 = 2.7, sn2 = 0.7, sn13 = 3.8 }

[[kalonymus.macropterus]]
key = "H"
value = { sn123 = 0.6, sn2 = 0.8, sn13 = 0.5 }

[[kalonymus.macropterus]]
key = "O"
value = { sn123 = 19.8, sn2 = 33.0, sn13 = 14.8 }

[[kalonymus.macropterus]]
key = "L"
value = { sn123 = 30.2, sn2 = 60.0, sn13 = 17.6 }

[[kalonymus.macropterus]]
key = "Ln"
value = { sn123 = 2.6, sn2 = 5.4, sn13 = 1.4 }

# Kalonymus Maximowiczianus

[[kalonymus.maximowiczianus]]
key = "P"
value = { sn123 = 34.4, sn2 = 0.0, sn13 = 49.5 }

[[kalonymus.maximowiczianus]]
key = "St"
value = { sn123 = 3.0, sn2 = 0.0, sn13 = 5.0 }

[[kalonymus.maximowiczianus]]
key = "H"
value = { sn123 = 0.7, sn2 = 0.1, sn13 = 1.0 }

[[kalonymus.maximowiczianus]]
key = "O"
value = { sn123 = 29.9, sn2 = 40.3, sn13 = 25.6 }

[[kalonymus.maximowiczianus]]
key = "L"
value = { sn123 = 30.9, sn2 = 57.8, sn13 = 18.2 }

[[kalonymus.maximowiczianus]]
key = "Ln"
value = { sn123 = 1.0, sn2 = 1.7, sn13 = 0.7 }

# Kalonymus Sachalinensis

[[kalonymus.sachalinensis]]
key = "P"
value = { sn123 = 33.7, sn2 = 0.4, sn13 = 47.1 }

[[kalonymus.sachalinensis]]
key = "St"
value = { sn123 = 5.3, sn2 = 0.0, sn13 = 9.6 }

[[kalonymus.sachalinensis]]
key = "H"
value = { sn123 = 0.4, sn2 = 0.0, sn13 = 0.6 }

[[kalonymus.sachalinensis]]
key = "O"
value = { sn123 = 47.2, sn2 = 68.2, sn13 = 39.2 }

[[kalonymus.sachalinensis]]
key = "L"
value = { sn123 = 11.9, sn2 = 30.8, sn13 = 2.9 }

[[kalonymus.sachalinensis]]
key = "Ln"
value = { sn123 = 0.7, sn2 = 0.6, sn13 = 0.6 }
