name = "Kalonymus Maximowiczianus"

[[fatty_acids]]
data = { tag123 = 34.4, mag2 = 0.0, dag1223 = 49.5 }
description = "16:0"
formula = "C16H32O2"
label = "P"

[[fatty_acids]]
data = { tag123 = 0.7, mag2 = 0.1, dag1223 = 1.0 }
description = "16:1"
formula = "C16H30O2"
label = "H"

[[fatty_acids]]
data = { tag123 = 3.0, mag2 = 0.0, dag1223 = 5.0 }
description = "18:0"
formula = "C18H36O2"
label = "St"

[[fatty_acids]]
data = { tag123 = 29.9, mag2 = 40.3, dag1223 = 25.6 }
description = "18:1"
formula = "C18H34O2"
label = "O"

[[fatty_acids]]
data = { tag123 = 30.9, mag2 = 57.8, dag1223 = 18.2 }
description = "18:2"
formula = "C18H32O2"
label = "L"

[[fatty_acids]]
data = { tag123 = 1.0, mag2 = 1.7, dag1223 = 0.7 }
description = "18:3"
formula = "C18H30O2"
label = "Ln"
