name = "Kalonymus Latifolius"

[[fatty_acids]]
data = { tag123 = 19.1, mag2 = 0.2, dag1223 = 27.1 }
description = "16:0"
formula = "C16H32O2"
label = "P"

[[fatty_acids]]
data = { tag123 = 1.4, mag2 = 1.3, dag1223 = 1.4 }
description = "16:1"
formula = "C16H30O2"
label = "H"

[[fatty_acids]]
data = { tag123 = 2.0, mag2 = 0.0, dag1223 = 3.1 }
description = "18:0"
formula = "C18H36O2"
label = "St"

[[fatty_acids]]
data = { tag123 = 56.5, mag2 = 63.2, dag1223 = 54.2 }
description = "18:1"
formula = "C18H34O2"
label = "O"

[[fatty_acids]]
data = { tag123 = 18.4, mag2 = 30.7, dag1223 = 12.6 }
description = "18:2"
formula = "C18H32O2"
label = "L"

[[fatty_acids]]
data = { tag123 = 2.6, mag2 = 4.6, dag1223 = 1.7 }
description = "18:3"
formula = "C18H30O2"
label = "Ln"
