name = "Kalonymus Macropterus"

[[fatty_acids]]
data = { tag123 = 44.2, mag2 = 0.2, dag1223 = 62.0 }
description = "16:0"
formula = "C16H32O2"
label = "P"

[[fatty_acids]]
data = { tag123 = 0.6, mag2 = 0.8, dag1223 = 0.5 }
description = "16:1"
formula = "C16H30O2"
label = "H"

[[fatty_acids]]
data = { tag123 = 2.7, mag2 = 0.7, dag1223 = 3.8 }
description = "18:0"
formula = "C18H36O2"
label = "St"

[[fatty_acids]]
data = { tag123 = 19.8, mag2 = 33.0, dag1223 = 14.8 }
description = "18:1"
formula = "C18H34O2"
label = "O"

[[fatty_acids]]
data = { tag123 = 30.2, mag2 = 60.0, dag1223 = 17.6 }
description = "18:2"
formula = "C18H32O2"
label = "L"

[[fatty_acids]]
data = { tag123 = 2.6, mag2 = 5.4, dag1223 = 1.4 }
description = "18:3"
formula = "C18H30O2"
label = "Ln"
