[package]
name = "utca"
version = "0.3.4"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
eframe = { version = "0.23.0", features = [
    "default_fonts",
    "persistence",
    "wgpu",
] }
egui = "0.23.0"
egui_dnd = "0.5.1"
egui_dock = { version = "0.8.2", features = ["serde"] }
egui_ext = { git = "https://github.com/kgv/egui_ext" }
egui_extras = "0.23.0"
egui_plot = "0.23.0"
egui-notify = "0.10.0"
indexmap = { version = "2.1.0", features = ["serde"] }
itertools = "0.12.0"
maplit = "1.0.2"
molecule = { git = "https://github.com/ippras/molecule" }
nom = "7.1.3"
ordered-float = { version = "4.1.1", features = ["serde"] }
rawpointer = "0.2.1"
rfd = "0.12.1"
serde = { version = "1.0.192", features = ["derive", "std"] }
tabled = "0.14.0"
toml_edit = { version = "0.21.0", features = ["serde"] }
tracing = "0.1.40"

# poll-promise = "0.3.0"
# thiserror = "1.0.49"
# regex = "1.9.6"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# web
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
getrandom = { version = "0.2.11", features = ["js"] }
js-sys = "0.3.65"
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.88"
wasm-bindgen-futures = "0.4.38"
web-sys = { version = "0.3.65", features = ["FilePropertyBag"] }
# File, FilePropertyBag

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
