[package]
edition = "2021"
name = "utca"
version = "0.4.0"

[dependencies]
anyhow = "1.0.79"
eframe = { version = "0.26.1", features = [
    "default_fonts",
    "persistence",
    # "wgpu",
] }
egui = "0.26.1"
egui-notify = "0.13.0"
egui_animation = "0.3.0"
egui_dnd = "0.7.0"
egui_dock = { version = "0.11.1", features = ["serde"] }
egui_ext = { git = "https://github.com/kgv/egui_ext" }
egui_extras = "0.26.1"
egui_plot = "0.26.1"
indexmap = { version = "2.2.3", features = ["serde"] }
itertools = "0.12.1"
maplit = "1.0.2"
molecule = { git = "https://github.com/ippras/molecule" }
ndarray = "0.15.6"
ndarray-stats = "0.5.1"
nom = "7.1.3"
ordered-float = { version = "4.2.0", features = ["serde"] }
rawpointer = "0.2.1"
rfd = "0.13.0"
serde = { version = "1.0.196", features = ["derive", "std"] }
simple-easing = "1.0.1"
tabled = "0.15.0"
toml_edit = { version = "0.22.4", features = ["serde"] }
tracing = "0.1.40"
uom = "0.35.0"

# poll-promise = "0.3.0"
# thiserror = "1.0.49"
# regex = "1.9.6"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# web
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
getrandom = { version = "0.2.12", features = ["js"] }
js-sys = "0.3.68"
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.91"
wasm-bindgen-futures = "0.4.41"
web-sys = { version = "0.3.68", features = ["FilePropertyBag"] }
# File, FilePropertyBag

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
