[package]
edition = "2021"
name = "utca"
version = "0.1.5"

[dependencies]
anyhow = "1.0"
base64 = "0.21"
eframe = { version = "0.22", features = [
    "default_fonts",
    "persistence",
    "wgpu",
] }
egui = "0.22"
egui-notify = "0.9"
egui_dnd = "0.5"
egui_dock = { version = "0.6", features = ["serde"] }
egui_ext = { git = "https://github.com/kgv/egui_ext" }
egui_extras = { version = "0.22", features = ["image"] }
indexmap = { version = "2.0", features = ["serde"] }
itertools = "0.11"
maplit = "1.0"
molecule = { git = "https://github.com/ippras/molecule" }
nom = "7.1"
ordered-float = { version = "3.7", features = ["serde"] }
poll-promise = "0.3"
rawpointer = "0.2"
regex = "1.8"
serde = { version = "1.0", features = ["derive", "std"] }
toml_edit = { version = "0.19", features = ["serde"] }
tracing = "0.1"

rfd = "0.11"
thiserror = "1.0"
# egui_file = "0.5.4"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# web
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
getrandom = { version = "0.2", features = ["js"] }
tracing-wasm = "0.2"
wasm-bindgen-futures = "0.4"

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
