[package]
name = "utca"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
base64 = "0.21.4"
eframe = { version = "0.23.0", features = [
    "default_fonts",
    "persistence",
    "wgpu",
] }
egui = "0.23.0"
egui_dnd = "0.5.1"
egui_dock = { version = "0.8.1", features = ["serde"] }
egui_ext = { git = "https://github.com/kgv/egui_ext" }
egui_extras = "0.23.0"
egui_plot = "0.23.0"
egui-notify = "0.10.0"
indexmap = { version = "2.0.2", features = ["serde"] }
itertools = "0.11.0"
maplit = "1.0.2"
molecule = { git = "https://github.com/ippras/molecule" }
nom = "7.1.3"
rawpointer = "0.2.1"
rfd = "0.12.1"
serde = { version = "1.0.189", features = ["derive", "std"] }
toml_edit = { version = "0.20.2", features = ["serde"] }
tracing = "0.1.40"
tabled = "0.14.0"

# poll-promise = "0.3.0"
# thiserror = "1.0.49"
# regex = "1.9.6"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

# web
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
getrandom = { version = "0.2.10", features = ["js"] }
js-sys = "0.3.64"
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = ["FilePropertyBag"] }
# File, FilePropertyBag

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
