[package]
edition = "2021"
name = "utca"
version = "0.1.2"

[dependencies]
anyhow = "1.0.71"
eframe = { version = "0.22.0", features = [
    "default_fonts",
    "persistence",
    "wgpu",
] }
egui = "0.22.0"
egui-notify = "0.7.0"
egui_dock = { version = "0.6.3", features = ["serde"] }
egui_extras = { version = "0.22.0", features = ["image"] }
indexmap = { version = "2.0.0", features = ["serde"] }
itertools = "0.11.0"
maplit = "1.0.2"
molecule = { git = "https://github.com/ippras/molecule" }
nom = "7.1.3"
ordered-float = { version = "3.7.0", features = ["serde"] }
poll-promise = "0.2.0"
rawpointer = "0.2.1"
regex = "1.8.4"
serde = { version = "1.0.164", features = ["derive", "std"] }
toml_edit = { version = "0.19.11", features = ["serde"] }
tracing = "0.1.37"

egui_dnd = "0.4.0"
getrandom = { version = "0.2.10", features = ["js"] }
rfd = "0.11.4"
thiserror = "1.0.40"

# egui_file = "0.5.4"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

# web
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2.1"
wasm-bindgen-futures = "0.4.33"

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
