= UTCA

Ultimate TAG Calculation Application

image:https://img.shields.io/crates/v/bevy_fluent.svg[crates.io, link=https://crates.io/crates/bevy_fluent]
image:https://docs.rs/bevy_fluent/badge.svg[docs.rs, link=https://docs.rs/bevy_fluent]
image:https://img.shields.io/crates/l/bevy_fluent[license, link==license]
image:https://github.com/kgv/bevy_fluent/workflows/ci/badge.svg[ci, link=https://github.com/kgv/bevy_fluent/actions]
image:https://img.shields.io/badge/bevy%20tracking-main-yellow[bevy tracking, link=https://github.com/bevyengine/bevy/blob/master/docs/plugins_guidelines.md=master-branch-tracking]

== Run

[source]
$Env:RUST_LOG="debug"

=== Native

`cargo run`

=== Web (http://127.0.0.1:8080)

`trunk serve --release --filehash=false`

==== Requirements

`rustup target add wasm32-unknown-unknown`

==== Errors

integrity:

* `chrome://settings/clearBrowserData`
* `Дополнительные`
* `Изображения и другие файлы, сохраненные в кеше`
* `Удалить данные`

== Doc

[Mass fraction](https://en.wikipedia.org/wiki/Mole_fraction#Mass_fraction)
[Mole fraction](https://en.wikipedia.org/wiki/Mole_fraction)

Метод простой нормировки. Для его использования необходимо, чтобы на хроматограмме были зарегистрированы все компоненты, входящие в состав анализируемой смеси. Сумму площадей всех пиков принимают за 1. Тогда отношение площади одного пика к сумме площадей, будет характеризовать массовую долю компонента в смеси.

Мольную долю компонента в смеси мо.

== See also

* https://byrdwell.com/Triacylglycerols/TAGbyMass1.htm[byrdwell.com]
* https://physics.nist.gov/cgi-bin/Compositions/stand_alone.pl[nist.gov, title=Atomic Weights and Isotopic Compositions for All Elements]
* https://tableconvert.com[tableconvert.com, title=Table converter]
* https://github.com/hkBst/tic-tac-toe-seed/blob/main/.github/workflows/deploy.yml[workflows example]

$env:RUST_LOG="utca=trace"

14:0 - Myr
16:0 - Pam
7-16:1 - P7x
9-16:1 - Pol
16:3 - Rug
18:0 - Ste
9-18:1 - Ole
11-18:1 - Vac
9,12-18:2 - Lin
9,12,15-18:3 - Lnn
20:0 - Ara
11-20:1 -Gad
13-20:1 - Gvc
22:0 - Beh
13-22:1 - Eru
15-22:1 - E15
24:0 - Lig
15-24:1 - Ner

14:0 - M
16:0 - P
16:1 - Po
16:3 - R
18:0 - S
9-18:1 - O
11-18:1 - V
18:2 - L
18:3 - Ln
20:0 - A
20:1 - G
20:2 - Gd
22:1 - E
24:1 - N

// https://raw.githubusercontent.com/ippras/utca/gh-pages/configs/lunaria_rediviva/1.1.utca.toml


