# https://byrdwell.com/Triacylglycerols/FattyAcids.htm

fa_4 =
    .abbreviation = Bu
    .common_name = Butyric acid
    .systematic_name = Butanoic acid
fa_5 =
    .abbreviation = V
    .common_name = Valeric acid
    .systematic_name = Pentanoic acid
fa_6 =
    .abbreviation = Co
    .common_name = Caproic acid
    .systematic_name = Hexanoic acid
fa_7 =
    .abbreviation = En
    .common_name = Enanthic acid
    .systematic_name = Heptanoic acid
fa_8 =
    .abbreviation = Cy
    .common_name = Caprylic acid
    .systematic_name = Octanoic acid
fa_9 =
    .common_name = Pelargonic acid
    .systematic_name = Nonanoic acid
fa_10 =
    .abbreviation = Ca
    .common_name = Capric acid
    .systematic_name = Decanoic acid
fa_11 =
    .common_name = Undecylic acid
    .systematic_name = Hendecanoic acid
fa_12 =
    .abbreviation = La
    .common_name = Lauric acid
    .systematic_name = Dodecanoic acid
fa_13 =
    .common_name = Tridecylic acid
    .systematic_name = Tridecanoic acid
fa_14 =
    .abbreviation = M
    .common_name = Myristic acid
    .systematic_name = Tetradecanoic acid
fa_15 =
    .common_name = Pentadecylic acid
    .systematic_name = Pentadecanoic acid
fa_16 =
    .abbreviation = P
    .common_name = Palmitic acid
    .systematic_name = Hexadecanoic acid
fa_16-9c =
    .abbreviation = Po
    .common_name = Palmitoleic acid
    .systematic_name = c-9-Hexadecenoic acid
fa_16-9t =
    .abbreviation = Pe
    .common_name = Palmitelaidic acid
    .systematic_name = t-9-Hexadecenoic acid
fa_17 =
    .common_name = Margaric acid
    .systematic_name = Heptadecanoic acid
fa_18 =
    .abbreviation = S
    .common_name = Stearic acid
    .systematic_name = Octadecanoic acid
fa_18-9c =
    .abbreviation = O
    .common_name = Oleic acid
    .systematic_name = c-9-Octadecenoic acid
fa_18-9t =
    .abbreviation = El
    .common_name = Elaidic acid
    .systematic_name = t-9-Octadecenoic acid
fa_18-9c12c =
    .abbreviation = L
    .common_name = Linoleic acid
    .systematic_name = c-9,12-Octadecadienoic acid
fa_18-9c12c15c =
    .abbreviation = Ln
    .common_name = a-Linolenic acid
    .systematic_name = c-9,12,15-Octadecatrienoic acid
fa_18-6c9c12c =
    .abbreviation = g-Ln
    .common_name = g-Linolenic acid, GLA
    .systematic_name = c-6,9,12-Octadecatrienoic acid
fa_18-9c11t13t =
    .abbreviation = Eo
    .common_name = a-Eleostearic acid
    .systematic_name = 9c,11t,13t-Octadecatrienoic acid
fa_18-9t11t13t =
    .common_name = b-Eleostearic acid
    .systematic_name = 9t,11t,13t-Octadecatrienoic acid
fa_18-8c10t12c =
    .abbreviation = Ja
    .common_name = Jacaric acid
    .systematic_name = 8c,10t,12c-Octadecatrienoic acid
fa_18-9t11t13c =
    .abbreviation = Ct
    .common_name = Catalpic acid
    .systematic_name = 9t,11t,13c-Octadecatrienoic acid
fa_18-6c9c12c15c =
    .abbreviation = St
    .common_name = Stearidonic acid
    .systematic_name = c-6,9,12,15-Octadecatetraenoic acid
fa_19 =
    .common_name = Nonadecylic acid
    .systematic_name = Nonadecanoic acid
fa_20 =
    .abbreviation = A
    .common_name = Arachidic acid
    .systematic_name = Eicosanoic acid
fa_20-9c =
    .abbreviation = G
    .common_name = Gadoleic acid
    .systematic_name = c-9-Eicosenoic acid
fa_20-11c =
    .abbreviation = Go
    .common_name = Gondoic acid
    .systematic_name = c-11-Eicosenoic acid
fa_20-11c14c =
    .common_name = DihomoLinoleic acid
    .systematic_name = c-11,14-Eicosadienoic acid
fa_20-11c14c17c =
    .common_name = Bis-homo-a-Linolenic acid, ETA
    .systematic_name = c-11,14,17-Eicosatrienoic acid
fa_20-8c11c14c =
    .common_name = Bis-homo-g-Linolenic acid
    .systematic_name = c-8,11,14-Eicosatrienoic acid
fa_20-5c8c11c =
    .common_name = Mead acid
    .systematic_name = c-5,8,11-Eicosatrienoic acid
fa_20-5c8c11c14c =
    .abbreviation = Ao
    .common_name = Arachidonic acid
    .systematic_name = c-5,8,11,14-Eicosatetraenoic acid
fa_20-8c11c14c17c =
    .common_name = Eicosatetraenoic acid
    .systematic_name = c-8,11,14,17-Eicosatetraenoic acid
fa_20-5c8c11c14c17c =
    .abbreviation = Ep
    .common_name = EPA
    .systematic_name = c-5,8,11,14,17-EicosaPentaenoic acid
fa_21 =
    .common_name = Heneicosylic acid
    .systematic_name = Heneicosanoic acid
fa_22 =
    .abbreviation = B
    .common_name = Behenic acid
    .systematic_name = Docosanoic acid
fa_22-13c =
    .abbreviation = E
    .common_name = Erucic acid
    .systematic_name = c-13-Docosenoic acid
fa_22-13c16c =
    .common_name = Docosadienoic acid
    .systematic_name = c-13,16-Docosadienoic acid
fa_22-5c13c16c =
    .common_name = Eranthic acid
    .systematic_name = c-5,13,16-Docosatrienoic acid
fa_22-7c10c13c16c =
    .common_name = Adrenic acid
    .systematic_name = c-7,10,13,16-Docosatetraenoic acid
fa_22-7c10c13c16c19c =
    .abbreviation = Dp
    .common_name = DPA
    .systematic_name = c-7,10,13,16,19-DocosaPentaenoic acid
fa_22-4c7c10c13c16c19c =
    .abbreviation = Dh
    .common_name = DHA
    .systematic_name = c-4,7,10,13,16,19-DocosaHexaenoic acid
fa_23 =
    .common_name = Tricosylic acid
    .systematic_name = Tricosanoic acid
fa_24 =
    .abbreviation = Lg
    .common_name = Lignoceric acid
    .systematic_name = Tetracosanoic acid
fa_24-15c =
    .abbreviation = N
    .common_name = Nervonic acid
    .systematic_name = c-15-Tetracosenoic acid
fa_24-15c18c =
    .common_name = Tetracosadienoic acid
    .systematic_name = c-15,18-Tetracosadienoic acid
fa_24-12c15c18c =
    .common_name = Tetracosatrienylic acid
    .systematic_name = c-12,15,18-Tetracosatrienoic acid
fa_24-9c12c15c18c =
    .common_name = Tetracosatetraenylic acid
    .systematic_name = c-9,12,15,18-Tetracosatetraenoic acid
fa_24-6c9c12c15c18c =
    .common_name = Tetracosapentaenylic acid
    .systematic_name = c-6,9,12,15,18-Tetracosapentaenoic acid
fa_24-6c9c12c15c18c21c =
    .common_name = Tetracosahexaenylic acid
    .systematic_name = c-6,9,12,15,18,21-Tetracosahexaenoic acid
fa_25 =
    .common_name = Hyenic acid
    .systematic_name = Pentacosanoic acid
fa_26 =
    .abbreviation = Ce
    .common_name = Cerotic acid
    .systematic_name = Hexacosanoic acid
fa_26-17c =
    .abbreviation = Xi
    .common_name = Ximenic acid
    .systematic_name = c-17-Hexacosenoic acid
fa_26- =
    .common_name = Hexacosadienylic acid
    .systematic_name = Hexacosadienoic acid
fa_26- =
    .common_name = Hexacosatrienylic acid
    .systematic_name = Hexacosatrienoic acid
fa_26- =
    .common_name = Hexacosatetraenylic acid
    .systematic_name = Hexacosatetraenoic acid
fa_26- =
    .common_name = Hexacosapentaenylic acid
    .systematic_name = Hexacosapentaenoic acid
fa_26- =
    .common_name = Hexacosahexaenylic acid
    .systematic_name = Hexacosahexaenoic acid
fa_27 =
    .common_name = Carboceric acid
    .systematic_name = Heptacosanoic acid
fa_28 =
    .abbreviation = Mo
    .common_name = Montanic acid
    .systematic_name = Octacosanoic acid
fa_28- =
    .common_name = Octacosenylic acid
    .systematic_name = Octacosenoic acid
fa_28- =
    .systematic_name = Octacosadienoic acid
fa_29 =
    .common_name = Nonacosylic acid
    .systematic_name = Nonacosanoic acid
fa_30 =
    .common_name = Melissic acid
    .systematic_name = Triacontanoic acid
fa_30-21c =
    .common_name = Lumequeic acid
    .systematic_name = c-21-Triacontenoic acid
fa_31 =
    .common_name = Henatriacontylic acid
    .systematic_name = Henatriacontanoic acid
fa_32 =
    .common_name = Lacceroic acid
    .systematic_name = Dotriacontanoic acid
fa_32- =
    .common_name = Dotriacontenylic acid
    .systematic_name = Dotriacontenoic acid
fa_32- =
    .systematic_name = Dotriacontadienoic acid
fa_33 =
    .common_name = Psyllic acid
    .systematic_name = Triatriacontanoic acid
fa_34 =
    .common_name = Gheddic acid
    .systematic_name = Tetratriacontanoic acid
fa_34- =
    .common_name = Tetratriacontenylic acid
    .systematic_name = Tetratriacontenoic acid
fa_34- =
    .systematic_name = Tetratriacontadienoic acid
fa_35 =
    .common_name = Ceroplastic acid
    .systematic_name = Pentatriacontanoic acid
fa_36 =
    .common_name = Hexatriacontylic acid
    .systematic_name = Hexatriacontanoic acid
fa_36- =
    .common_name = Hexatriacontenylic acid
    .systematic_name = Hexatriacontenoic acid
fa_36- =
    .systematic_name = Hexatriacontadienoic acid