abbreviation = аббревиатура
adduct = аддукт
ascending = по возрастанию
ascending_description = обратный порядок (от максимума к минимуму)
calculation = вычисление
common_name = общее название
composition = композиция
configuration = конфигурация
dag = ДАГ
descending = по убыванию
descending_description = прямой порядок (от минимума к максимуму)
diacylglycerol = диацилглицерин
edit = изменить
experimental = экспериментальное значение
fa = ЖК
fatty_acid = { -fatty_acid_term }
fatty_acid_mass = { mass } { -fatty_acid_term(genus: "genitive") }
formula = формула
fraction = доля
group = группировка
gunstone = Ганстоун
gunstone_description = вычисление по теории Ганстоуна
key = ключ
key_description = сортировать по ключу
left_panel = левая панель
mag = МАГ
mass = масса
mass_fraction = массовая доля
method = метод
methyl_ester_mass = { mass } метилового эфира
mixture_molar_mass = молярная { mass } смеси
molar_mass = молярная { mass }
mole_fraction = мольная доля
monoacylglycerol = моноацилглицерин
names = названия
names_description = показать устоявшиеся названия для жирных кислот
order = порядок
percent = проценты
precision = точность
properties = свойства
properties_description = показать { properties }
reset_application = сбросить данные приложения
reset_gui = сбросить настройки интерфейса
resize = изменить размер
selectivity_factor = фактор селективности
sign = знак
signed = со знаком
signed_description = теоретически рассчитанные отрицательные значения отстаются без изменения
sort = сотрировка
systematic_name = систематическое название
tag = ТАГ
theoretical = теоретическое значение
triacylglycerol = триацилглицерин
unsigned = без знака
unsigned_description = теоретически рассчитанные отрицательные значения замещаются нулем
value = значение
value_description = сортировать по значению
vander_wal = Вандер Валь
vander_wal_description = вычисление по теории Вандер Валя

-fatty_acid_term = { $genus ->
   *[nominative] жирная кислота
    [genitive] жирной кислоты
}
