name = "Olea SH"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 168935.0 }
formula = "H24C12O2"
label = "Lau"

[[fatty_acids]]
data = { mag2 = 255312.0, dag1223 = 0.0, tag123 = 1151054.0 }
formula = "H28C14O2"
label = "Myr"

[[fatty_acids]]
data = { mag2 = 6600210.0, dag1223 = 0.0, tag123 = 116744609.0 }
formula = "H32C16O2"
label = "Pam"

[[fatty_acids]]
data = { mag2 = 547485.0, dag1223 = 0.0, tag123 = 4442301.0 }
formula = "H30C16O2"
label = "Hx7"

[[fatty_acids]]
data = { mag2 = 266486.0, dag1223 = 0.0, tag123 = 1811187.0 }
formula = "H30C16O2"
label = "Hx9"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 0.0 }
formula = "H28C16O2"
label = "Pl7"

[[fatty_acids]]
data = { mag2 = 2036059.0, dag1223 = 0.0, tag123 = 30934021.0 }
formula = "H36C18O2"
label = "Ste"

[[fatty_acids]]
data = { mag2 = 52940620.0, dag1223 = 0.0, tag123 = 247227446.0 }
formula = "H34C18O2"
label = "Ole"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 10702708.0 }
formula = "H34C18O2"
label = "Vac"

[[fatty_acids]]
data = { mag2 = 35163351.0, dag1223 = 0.0, tag123 = 135296626.0 }
formula = "H32C18O2"
label = "Lin"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 9932595.0 }
formula = "H38C20O2"
label = "Gad"

[[fatty_acids]]
data = { mag2 = 69007867.0, dag1223 = 0.0, tag123 = 346143252.0 }
formula = "H30C18O2"
label = "Lnn"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 0.0 }
formula = "H34C20O2"
label = "Etr"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 0.0 }
formula = "H32C18O2"
label = "Ody"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 0.0 }
formula = "H30C16O2"
label = "Hx11"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 4103158.0 }
formula = "H40C20O2"
label = "Ara"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 0.0 }
formula = "H36C20O2"
label = "Edn"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 0.0 }
formula = "H44C22O2"
label = "Beh"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 0.0 }
formula = "H42C22O2"
label = "Eru"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 0.0 }
formula = "H48C24O2"
label = "Lig"
