name = "Panax"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 54063.0 }
formula = "H24C12O2"
label = "Lau"

[[fatty_acids]]
data = { mag2 = 1.0, dag1223 = 0.0, tag123 = 550829.0 }
formula = "H28C14O2"
label = "Myr"

[[fatty_acids]]
data = { mag2 = 1200130.0, dag1223 = 2300389.0, tag123 = 30977748.0 }
formula = "H32C16O2"
label = "Pam"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 295524.0 }
formula = "H30C16O2"
label = "Hx7"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 83334.0 }
formula = "H30C16O2"
label = "Hx9"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 88276.0 }
formula = "H28C16O2"
label = "Pl7"

[[fatty_acids]]
data = { mag2 = 234788.0, dag1223 = 689257.0, tag123 = 11497698.0 }
formula = "H36C18O2"
label = "Ste"

[[fatty_acids]]
data = { mag2 = 3325164.0, dag1223 = 2701913.0, tag123 = 30682574.0 }
formula = "H34C18O2"
label = "Ole"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 270977.0 }
formula = "H34C18O2"
label = "Vac"

[[fatty_acids]]
data = { mag2 = 18837591.0, dag1223 = 17796103.0, tag123 = 178937172.0 }
formula = "H32C18O2"
label = "Lin"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 760634.0 }
formula = "H38C20O2"
label = "Gad"

[[fatty_acids]]
data = { mag2 = 400395.0, dag1223 = 0.0, tag123 = 9308764.0 }
formula = "H30C18O2"
label = "Lnn"

[[fatty_acids]]
data = { mag2 = 44241.0, dag1223 = 950168.0, tag123 = 351232.0 }
formula = "H34C20O2"
label = "Etr"

[[fatty_acids]]
data = { mag2 = 211749.0, dag1223 = 168519.0, tag123 = 339069.0 }
formula = "H32C18O2"
label = "Ody"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 0.0 }
formula = "H30C16O2"
label = "Hx11"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 0.0 }
formula = "H40C20O2"
label = "Ara"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 0.0 }
formula = "H36C20O2"
label = "Edn"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 0.0 }
formula = "H44C22O2"
label = "Beh"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 0.0 }
formula = "H42C22O2"
label = "Eru"

[[fatty_acids]]
data = { mag2 = 0.0, dag1223 = 0.0, tag123 = 0.0 }
formula = "H48C24O2"
label = "Lig"
