= Применение модели sn-1,2;3-статистического распределения ацилов жирных кислот в запасных триацилглицеринах микроводорослей рода Vischeria (штаммов H-242 и C-70 коллекции IPPAS) для оценки их биотехнологического потенциала
:showtitle:
:authors: Сидоров Р.А., Казаков Г.В., Стариков А. Ю., Синетова М.А.
:stem:
:table-caption: Таблица
ifndef::env-github[:toc:]

Микроводоросли-продуценты полиненасыщенных (ПНЖК) ω-3 жирных кислот (ЖК) давно привлекают внимание исследователей, так как эти ЖК играют важную роль в функционировании сердечнососудистой системы теплокровных, в том числе – человека (Khozin-Goldberg et al., 2011). Например, эйкозапентаеновая кислота (ЭПК, 20:5ω3) уже много лет рекомендуется как добавка в составе терапии и профилактики атеросклероза и тромбозов у человека (Liao et al., 2022). Положение жирной кислоты в молекуле три-ацилглицерина (ТАГ) влияет на его нутрицевтические свойства, окислительную стабильность, скорость адсорбции в желудочно-кишечном тракте, метаболизм и даже на атеро-генез (Mu and Porsgaard, 2005). Известно, что ЖК, ацилирующие sn-1 и sn-3 положения атомов углерода глицеринового остатка, лучше гидролизуются панкреатической липазой, а кислоты в sn-2-положении усваиваются в форме моноацилглицеринов; так, дети лучше усваивают пальмитиновую кислоту из sn-2-положения ТАГ жира материнского молока, чем из sn-1 или sn-3 положений ТАГ растительных масел (Quinlan and Moore, 1993). Показано, что лучшие нутрицевтические свойства проявляют ТАГ, содержащие в их sn2-положении ПНЖК – арахидоновую или ЭПК – такие ТАГ лучше абсорбируются, чем ТАГ с таким же ЖК составом, но в которых эти ЖК распределены случайным образом между sn-положениями углеродных атомов глицеринового остатка (Takeuci et al., 2002). В этой связи особый интерес представляют так называемые структурированные ТАГ (сТАГ), содержащие в их sn-2-положении ПНЖК или пальмитиновую кислоту – такие ТАГ обладают множеством ценных нутрицевтических свойств. Потенциальным источником таких сТАГ могут стать микроводоросли рода Vischeria, которые известны исследователям как суперпродуценты ЭПК (Sinetova et al., 2021).

Мы изучили жирнокислотный состав суммарных липидов (СЛ), запасных ТАГ и особенности распределения ЖК между sn-положениями остатка глицерина в них у клеток двух штаммов микроводорослей из рода Vischeria – IPPAS H-242 и С-70, культивируемых на среде BBM. Обнаружено более 20 индивидуальных ЖК, главными из которых были 16:0, 16:1, 18:1 и 20:5 – на их долю приходилось более 80% от суммы ЖК. Результаты ГХ-МС анализов представлены в табл. 1. Можно видеть, что в СЛ обоих штаммов содержалось высокое количество ЭПК – до 22,4% у клеток штамма С-70, однако она практически не запасалась в ТАГ – там её содержание было в 2–3,5 раза ниже, чем в СЛ. В ТАГ она ацилировала главным образом sn-1 и sn-3-положения, где её концентрация была в 3,6–9,4 раза выше, чем в sn-2-положениях, в то время, как пальмитиновая кислота была практически полностью сосредоточена в sn-2-положении ТАГ обоих исследованных штаммов. В связи с этим наблюдением представляло интерес рассчитать позиционно-видовой состав ТАГ этих микроводорослей, так как они могут содержать высокие количества сТАГ.

.Жирнокислотный состав суммарных липидов, триацилглицеринов и их sn-2, sn-1,3 положений у микроводорослей рода Vischeria, штаммы IPPAS H-242 и C-70
[cols="13*^", options="header"]
:fn-1: Минорные ЖК. Содержали 0,05-0,5% 12:0, 14:1ω9, 16:1ω5, 16:1ω7, 16:2ω9, 18:3ω6, 18:4ω6, 20:0, 20:3ω6, 22:0, 20:4ω3, 24:0.
:fn-2: pass:m[Вычислены по формуле stem:[[S\\]_{1,3} = (3[S\\]_{1,2,3} - [S\\]_2) / 2].]
|===
3.+|Жирные кислоты, +
мол.%|14:0 +
M|16:0 +
P|16:1 ω9 +
Po|18:0 +
S|18:1 ω9 +
O|18:2 ω6 +
L|18:3 ω3 +
Ln|20:4 ω6 +
A|20:5 ω3 +
E|Мfootnote:1[{fn-1}]

.4+|H-242
2.+|СЛ
|3,3|18,3|43,3|0,7|3,6|2,0|0,6|3,0|22,4|2,8

.3+|ТАГ
|sn-1,2,3|1,5|22,2|48,3|2,1|9,3|4,8|1,9|1,2|6,4|2,3
|sn-2|2,5|57,6|28,8|1,9|2,6|2,3|0,8|0,2|2,3|1,0
|sn-1,3footnote:2[{fn-2}]|1,0|4,5|58,1|2,3|12,6|6,0|2,4|1,7|8,4|3,0

.4+|C-70
2.+|СЛ
|2,9|23,0|36,9|0,8|8,7|3,9|0,5|5,2|14,4|3,7

.3+|ТАГ
|sn-1,2,3|1,8|21,0|54,0|0,6|9,2|1,9|0,2|1,6|7,7|2,0
|sn-2|2,5|59,9|22,9|2,9|3,7|4,2|1,3|0,2|1,4|1,0
|sn-1,3footnote:2[]|1,5|1,6|69,0|0,0|11,8|0,8|0,0|2,3|10,8|2,2
|===

Определение позиционно-видового состава (ПВС) ТАГ, несмотря на развитие современной техники, до сих пор является трудной задачей ввиду большого разнообразия ТАГ – так, для ТАГ клеток Н-242, содержащих 21 ЖК, количество молекулярных видов может достигать 9261. Для характеристики ПВС ТАГ изучаемых объектов мы применили разработанную нами программу UTCA (Ultimate Triacylglycerols Calculation Application), выполняющую расчет состава ТАГ на основании их ЖК-состава (sn-1,2,3-положений) и ЖК состава sn-2-положения, которое определяется как ЖК-состав sn-2-моноацилглицеринов, получаемых в результате липазного гидролиза ТАГ. Расчеты выполняются на основе хорошо зарекомендовавшей себя модели sn-1,3-статистического, 2-статистического распределения ЖК между sn-положениями углеродных атомов остатка глицерина.

Результаты вычислений отражены в табл. 2, в которой приведены молекулярные виды ТАГ с массовой долей более 1% от суммы ТАГ. Можно видеть, что в клетках IPPAS Н-242 и С-70 на сумму 14 молекулярных видов приходится 66,6% и 77,4% ТАГ соответственно, 7 видов из них относятся к USU типу, где U и S – ацилы ненасыщенных и насыщенных ЖК соответственно.

.Позиционно-видовой состав ТАГ клеток микроводорослей рода Vischeria, штаммы IPPAS H-242 и C-70
[cols="4*^", options="header"]
|===
|Тип|Вид|H-242|C-70

.6+.^|UUU
|PoPoPo|9,7|10,9
|PoPoO|4,2|3,7
|PoPoE|2,8|3,4
|PoPoL|2,0|-
|PoLPo|-|2,0
|PoOPo|-|1,8

.9+.^|USU
|PoPPo|19,4|28,5
|PoPO|8,5|9,7
|PoPA|1,2|1,9
|PoPE|5,6|8,9
|PoPL|4,0|-
|OPE|1,6|1,5
|PoSPo|-|1,4
|PoMPo|-|1,2
|PoPLn|1,6|-

.3+.^|SSU
|PPPo|3,0|1,3
|SPPo|1,5|-
|MPPo|-|1,2

|SUU|PPoPo|1,5|-
|===

Несмотря на высокое сходство позиционно-видового состава ТАГ, клетки штамма
IPPAS С-70 запасали в 1,5 раза больше
sn-1-пальмитолеил-2-пальмитоил-3-пальмитолеилглицерина, чем клетки IPPAS Н-242,
а суммарное содержание сТАГ в нём достигало 39,4% от суммы ТАГ, в то время как в
клетках штамма IPPAS Н-242 их количество составляло 29,5%.

Таким образом, изученные штаммы могут рассматриваться как естественный источник
структурированных ТАГ, содержащих в sn-2-положении пальмитиновую кислоту, а в
sn-1 и sn-3 – пальмитолеиновую. Известно, что пальмитолеиновая кислота участвует
в формировании и поддержании функционирования кардиомиоцитов в условиях
интенсивных физических нагрузок и способствует предотвращению развития
гипертрофической кардиомиопатии (Foryst-Ludwig and Kriessl, 2015).
