# clipboard api is still unstable, so web-sys requires the below flag to be
# passed for copy (ctrl + c) to work [unstable-apis], [check status].
#
# We don't use `[build]` because of rust analyzer's build cache invalidation
# https://github.com/emilk/eframe_template/issues/93
#
# check status: https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Clipboard.html
# unstable-apis: https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html
[target.wasm32-unknown-unknown]
rustflags = ["--cfg=web_sys_unstable_apis"]