# Euonymus Euonymus

[euonymus.euonymus.bungeanus]
sn-123 = { P = 28.1, St = 1.5, H = 10.2, O = 17.2, L = 41.7, Ln = 1.3 }
sn-2 = { P = 0.0, St = 0.0, H = 0.2, O = 11.2, L = 86.4, Ln = 2.1 }
sn-13 = { P = 40.0, St = 2.4, H = 14.0, O = 21.0, L = 21.5, Ln = 1.0 }

[euonymus.euonymus.europaeus]
sn-123 = { P = 23.2, St = 1.5, H = 6.8, O = 20.5, L = 45.6, Ln = 2.5 }
sn-2 = { P = 0.0, St = 0.0, H = 2.7, O = 12.5, L = 81.1, Ln = 3.7 }
sn-13 = { P = 28.6, St = 2.8, H = 6.9, O = 26.8, L = 32.8, Ln = 2.1 }

[euonymus.euonymus.hamiltonianus]
sn-123 = { P = 33.6, St = 2.5, H = 2.0, O = 16.4, L = 44.0, Ln = 1.5 }
sn-2 = { P = 0.0, St = 0.3, H = 2.1, O = 15.0, L = 79.0, Ln = 2.8 }
sn-13 = { P = 47.3, St = 3.7, H = 1.7, O = 17.9, L = 28.4, Ln = 1.0 }

[euonymus.euonymus.phellomanus]
sn-123 = { P = 31.9, St = 5.3, H = 1.3, O = 18.3, L = 41.3, Ln = 1.8 }
sn-2 = { P = 0.4, St = 0.0, H = 0.0, O = 10.8, L = 86.6, Ln = 2.1 }
sn-13 = { P = 44.7, St = 8.8, H = 1.9, O = 22.6, L = 20.5, Ln = 1.5 }

[euonymus.euonymus.semiexsertus]
sn-123 = { P = 28.8, St = 1.6, H = 0.6, O = 16.6, L = 51.3, Ln = 1.2 }
sn-2 = { P = 0.1, St = 0.0, H = 0.2, O = 7.3, L = 90.5, Ln = 1.9 }
sn-13 = { P = 40.2, St = 2.5, H = 0.9, O = 21.8, L = 33.9, Ln = 0.8 }

[euonymus.euonymus.sieboldianus]
sn-123 = { P = 20.0, St = 2.1, H = 13.6, O = 25.5, L = 37.8, Ln = 1.0 }
sn-2 = { P = 0.1, St = 0.0, H = 7.0, O = 15.6, L = 75.4, Ln = 2.0 }
sn-13 = { P = 28.2, St = 3.3, H = 15.6, O = 31.5, L = 20.8, Ln = 0.6 }

# Euonymus Melanocarya

[euonymus.melanocarya.alatus]
sn-123 = { P = 24.6, St = 2.2, H = 0.5, O = 23.5, L = 46.4, Ln = 2.8 }
sn-2 = { P = 0.5, St = 0.1, H = 0.4, O = 18.4, L = 76.7, Ln = 3.9 }
sn-13 = { P = 34.1, St = 3.3, H = 0.4, O = 26.9, L = 33.0, Ln = 2.3 }

[euonymus.melanocarya.sacrosantcus]
sn-123 = { P = 22.3, St = 2.0, H = 0.1, O = 28.1, L = 44.6, Ln = 2.9 }
sn-2 = { P = 0.5, St = 0.3, H = 0.1, O = 16.8, L = 77.5, Ln = 4.9 }
sn-13 = { P = 30.4, St = 2.8, H = 1.4, O = 34.3, L = 29.1, Ln = 2.0 }

# Euonymus Pseudovyenomus

[euonymus.pseudovyenomus.pauciflorus]
sn-123 = { P = 26.7, St = 5.4, H = 1.0, O = 39.4, L = 26.5, Ln = 1.1 }
sn-2 = { P = 0.5, St = 0.0, H = 0.0, O = 43.6, L = 54.0, Ln = 1.9 }
sn-13 = { P = 36.8, St = 8.7, H = 1.3, O = 38.7, L = 13.8, Ln = 0.7 }

# Kalonymus

[kalonymus.latifolius]
sn-123 = { P = 19.1, St = 2.0, H = 1.4, O = 56.5, L = 18.4, Ln = 2.6 }
sn-2 = { P = 0.2, St = 0.0, H = 1.3, O = 63.2, L = 30.7, Ln = 4.6 }
sn-13 = { P = 27.1, St = 3.1, H = 1.4, O = 54.2, L = 12.6, Ln = 1.7 }

[kalonymus.macropterus]
sn-123 = { P = 44.2, St = 2.7, H = 0.6, O = 19.8, L = 30.2, Ln = 2.6 }
sn-2 = { P = 0.2, St = 0.7, H = 0.8, O = 33.0, L = 60.0, Ln = 5.4 }
sn-13 = { P = 62.0, St = 3.8, H = 0.5, O = 14.8, L = 17.6, Ln = 1.4 }

[kalonymus.maximowiczianus]
sn-123 = { P = 34.4, St = 3.0, H = 0.7, O = 29.9, L = 30.9, Ln = 1.0 }
sn-2 = { P = 0.0, St = 0.0, H = 0.1, O = 40.3, L = 57.8, Ln = 1.7 }
sn-13 = { P = 49.5, St = 5.0, H = 1.0, O = 25.6, L = 18.2, Ln = 0.7 }

[kalonymus.sachalinensis]
sn-123 = { P = 33.7, St = 5.3, H = 0.4, O = 47.2, L = 11.9, Ln = 0.7 }
sn-2 = { P = 0.4, St = 0.0, H = 0.0, O = 68.2, L = 30.8, Ln = 0.6 }
sn-13 = { P = 47.1, St = 9.6, H = 0.6, O = 39.2, L = 2.9, Ln = 0.6 }
