# https://byrdwell.com/Triacylglycerols/FattyAcids.htm

fa_0400 =
    .abbreviation = Bu
    .common_name = Butyric acid
    .systematic_name = Butanoic acid
fa_0500 =
    .abbreviation = V
    .common_name = Valeric acid
    .systematic_name = Pentanoic acid
fa_0600 =
    .abbreviation = Co
    .common_name = Caproic acid
    .systematic_name = Hexanoic acid
fa_0700 =
    .abbreviation = En
    .common_name = Enanthic acid
    .systematic_name = Heptanoic acid
fa_0800 =
    .abbreviation = Cy
    .common_name = Caprylic acid
    .systematic_name = Octanoic acid
fa_0900 =
    .common_name = Pelargonic acid
    .systematic_name = Nonanoic acid
fa_1000 =
    .abbreviation = Ca
    .common_name = Capric acid
    .systematic_name = Decanoic acid
fa_1100 =
    .common_name = Undecylic acid
    .systematic_name = Hendecanoic acid
fa_1200 =
    .abbreviation = La
    .common_name = Lauric acid
    .systematic_name = Dodecanoic acid
fa_1300 =
    .common_name = Tridecylic acid
    .systematic_name = Tridecanoic acid
fa_1400 =
    .abbreviation = M
    .common_name = Myristic acid
    .systematic_name = Tetradecanoic acid
fa_1500 =
    .common_name = Pentadecylic acid
    .systematic_name = Pentadecanoic acid
fa_1600 =
    .abbreviation = P
    .common_name = Palmitic acid
    .systematic_name = Hexadecanoic acid
fa_160109c =
    .abbreviation = Po
    .common_name = Palmitoleic acid
    .systematic_name = c-9-Hexadecenoic acid
fa_160109t =
    .abbreviation = Pe
    .common_name = Palmitelaidic acid
    .systematic_name = t-9-Hexadecenoic acid
fa_1700 =
    .common_name = Margaric acid
    .systematic_name = Heptadecanoic acid
fa_1800 =
    .abbreviation = S
    .common_name = Stearic acid
    .systematic_name = Octadecanoic acid
fa_180109c =
    .abbreviation = O
    .common_name = Oleic acid
    .systematic_name = c-9-Octadecenoic acid
fa_180109t =
    .abbreviation = El
    .common_name = Elaidic acid
    .systematic_name = t-9-Octadecenoic acid
fa_180209c12c =
    .abbreviation = L
    .common_name = Linoleic acid
    .systematic_name = c-9,12-Octadecadienoic acid
fa_180309c12c15c =
    .abbreviation = Ln
    .common_name = a-Linolenic acid
    .systematic_name = c-9,12,15-Octadecatrienoic acid
fa_180306c09c12c =
    .abbreviation = g-Ln
    .common_name = g-Linolenic acid, GLA
    .systematic_name = c-6,9,12-Octadecatrienoic acid
fa_180309c11t13t =
    .abbreviation = Eo
    .common_name = a-Eleostearic acid
    .systematic_name = 9c,11t,13t-Octadecatrienoic acid
fa_180309t11t13t =
    .common_name = b-Eleostearic acid
    .systematic_name = 9t,11t,13t-Octadecatrienoic acid
fa_180308c10t12c =
    .abbreviation = Ja
    .common_name = Jacaric acid
    .systematic_name = 8c,10t,12c-Octadecatrienoic acid
fa_180309t11t13c =
    .abbreviation = Ct
    .common_name = Catalpic acid
    .systematic_name = 9t,11t,13c-Octadecatrienoic acid
fa_180406c09c12c15c =
    .abbreviation = St
    .common_name = Stearidonic acid
    .systematic_name = c-6,9,12,15-Octadecatetraenoic acid
fa_1900 =
    .common_name = Nonadecylic acid
    .systematic_name = Nonadecanoic acid
fa_2000 =
    .abbreviation = A
    .common_name = Arachidic acid
    .systematic_name = Eicosanoic acid
fa_200109c =
    .abbreviation = G
    .common_name = Gadoleic acid
    .systematic_name = c-9-Eicosenoic acid
fa_200111c =
    .abbreviation = Go
    .common_name = Gondoic acid
    .systematic_name = c-11-Eicosenoic acid
fa_200211c14c =
    .common_name = DihomoLinoleic acid
    .systematic_name = c-11,14-Eicosadienoic acid
fa_200311c14c17c =
    .common_name = Bis-homo-a-Linolenic acid, ETA
    .systematic_name = c-11,14,17-Eicosatrienoic acid
fa_200308c11c14c =
    .common_name = Bis-homo-g-Linolenic acid
    .systematic_name = c-8,11,14-Eicosatrienoic acid
fa_200305c08c11c =
    .common_name = Mead acid
    .systematic_name = c-5,8,11-Eicosatrienoic acid
fa_200405c08c11c14c =
    .abbreviation = Ao
    .common_name = Arachidonic acid
    .systematic_name = c-5,8,11,14-Eicosatetraenoic acid
fa_200408c11c14c17c =
    .common_name = Eicosatetraenoic acid
    .systematic_name = c-8,11,14,17-Eicosatetraenoic acid
fa_200505c08c11c14c17c =
    .abbreviation = Ep
    .common_name = EPA
    .systematic_name = c-5,8,11,14,17-EicosaPentaenoic acid
fa_2100 =
    .common_name = Heneicosylic acid
    .systematic_name = Heneicosanoic acid
fa_2200 =
    .abbreviation = B
    .common_name = Behenic acid
    .systematic_name = Docosanoic acid
fa_220113c =
    .abbreviation = E
    .common_name = Erucic acid
    .systematic_name = c-13-Docosenoic acid
fa_220213c16c =
    .common_name = Docosadienoic acid
    .systematic_name = c-13,16-Docosadienoic acid
fa_220305c13c16c =
    .common_name = Eranthic acid
    .systematic_name = c-5,13,16-Docosatrienoic acid
fa_220407c10c13c16c =
    .common_name = Adrenic acid
    .systematic_name = c-7,10,13,16-Docosatetraenoic acid
fa_220507c10c13c16c19c =
    .abbreviation = Dp
    .common_name = DPA
    .systematic_name = c-7,10,13,16,19-DocosaPentaenoic acid
fa_220604c07c10c13c16c19c =
    .abbreviation = Dh
    .common_name = DHA
    .systematic_name = c-4,7,10,13,16,19-DocosaHexaenoic acid
fa_2300 =
    .common_name = Tricosylic acid
    .systematic_name = Tricosanoic acid
fa_2400 =
    .abbreviation = Lg
    .common_name = Lignoceric acid
    .systematic_name = Tetracosanoic acid
fa_240115c =
    .abbreviation = N
    .common_name = Nervonic acid
    .systematic_name = c-15-Tetracosenoic acid
fa_240215c18c =
    .common_name = Tetracosadienoic acid
    .systematic_name = c-15,18-Tetracosadienoic acid
fa_240312c15c18c =
    .common_name = Tetracosatrienylic acid
    .systematic_name = c-12,15,18-Tetracosatrienoic acid
fa_240409c12c15c18c =
    .common_name = Tetracosatetraenylic acid
    .systematic_name = c-9,12,15,18-Tetracosatetraenoic acid
fa_240506c09c12c15c18c =
    .common_name = Tetracosapentaenylic acid
    .systematic_name = c-6,9,12,15,18-Tetracosapentaenoic acid
fa_240606c09c12c15c18c21c =
    .common_name = Tetracosahexaenylic acid
    .systematic_name = c-6,9,12,15,18,21-Tetracosahexaenoic acid
fa_2500 =
    .common_name = Hyenic acid
    .systematic_name = Pentacosanoic acid
fa_2600 =
    .abbreviation = Ce
    .common_name = Cerotic acid
    .systematic_name = Hexacosanoic acid
fa_260117c =
    .abbreviation = Xi
    .common_name = Ximenic acid
    .systematic_name = c-17-Hexacosenoic acid
fa_2600 =
    .common_name = Hexacosadienylic acid
    .systematic_name = Hexacosadienoic acid
fa_2600 =
    .common_name = Hexacosatrienylic acid
    .systematic_name = Hexacosatrienoic acid
fa_2600 =
    .common_name = Hexacosatetraenylic acid
    .systematic_name = Hexacosatetraenoic acid
fa_2600 =
    .common_name = Hexacosapentaenylic acid
    .systematic_name = Hexacosapentaenoic acid
fa_2600 =
    .common_name = Hexacosahexaenylic acid
    .systematic_name = Hexacosahexaenoic acid
fa_2700 =
    .common_name = Carboceric acid
    .systematic_name = Heptacosanoic acid
fa_2800 =
    .abbreviation = Mo
    .common_name = Montanic acid
    .systematic_name = Octacosanoic acid
fa_2800 =
    .common_name = Octacosenylic acid
    .systematic_name = Octacosenoic acid
fa_2800 =
    .systematic_name = Octacosadienoic acid
fa_2900 =
    .common_name = Nonacosylic acid
    .systematic_name = Nonacosanoic acid
fa_3000 =
    .common_name = Melissic acid
    .systematic_name = Triacontanoic acid
fa_300121c =
    .common_name = Lumequeic acid
    .systematic_name = c-21-Triacontenoic acid
fa_3100 =
    .common_name = Henatriacontylic acid
    .systematic_name = Henatriacontanoic acid
fa_3200 =
    .common_name = Lacceroic acid
    .systematic_name = Dotriacontanoic acid
fa_3200 =
    .common_name = Dotriacontenylic acid
    .systematic_name = Dotriacontenoic acid
fa_3200 =
    .systematic_name = Dotriacontadienoic acid
fa_3300 =
    .common_name = Psyllic acid
    .systematic_name = Triatriacontanoic acid
fa_3400 =
    .common_name = Gheddic acid
    .systematic_name = Tetratriacontanoic acid
fa_3400 =
    .common_name = Tetratriacontenylic acid
    .systematic_name = Tetratriacontenoic acid
fa_3400 =
    .systematic_name = Tetratriacontadienoic acid
fa_3500 =
    .common_name = Ceroplastic acid
    .systematic_name = Pentatriacontanoic acid
fa_3600 =
    .common_name = Hexatriacontylic acid
    .systematic_name = Hexatriacontanoic acid
fa_3600 =
    .common_name = Hexatriacontenylic acid
    .systematic_name = Hexatriacontenoic acid
fa_3600 =
    .systematic_name = Hexatriacontadienoic acid