abbreviation = abbreviation
adduct = adduct
as_is = as is
ascending = ascending
ascending_description = reverse order (from max to min)
calculation = calculation
common_name = common name
composition = composition
configuration = configuration
dag = DAG
descending = descending
descending_description = direct order (from min to max)
diacylglycerol = diacylglycerol
edit = edit
experimental = experimental
fa = FA
fatty_acid = { -fatty_acid_term }
fatty_acid_mass = { -fatty_acid_term } { mass }
formula = formula
fraction = fraction
group = group
gunstone = Gunstone
gunstone_description = calculate by { gunstone }'s theory
key = key
key_description = sort by key
left_panel = left panel
mag = MAG
mass = mass
method = method
methyl_ester_mass = methyl ester { mass }
molar_mass = molar { mass }
monoacylglycerol = monoacylglycerol
names = names
names_description = show names for fatty acids
order = order
percent = percent
precision = precision
properties = properties
properties_description = show { properties }
reset_application = reset application
reset_gui = reset GUI
resize = resize table columns
selectivity_factor = selectivity factor
sign = sign
signed = signed
signed_description = theoretically calculated negative values are as is
sort = sort
species = species
systematic_name = systematic name
tag = TAG
theoretical = theoretical
to_mass_fraction = to mass fraction
to_mole_fraction = to mole fraction
triacylglycerol = triacylglycerol
unsigned = unsigned
unsigned_description = theoretically calculated negative values are replaced with zeros
value = value
value_description = sort by value
vander_wal = Vander Wal
vander_wal_description = calculate by { vander_wal }'s theory

-fatty_acid_term = fatty acid
