name = "Lunaria 1.1"

[[fatty_acids]]
label = "Methyl tetradecanoate"
formula = "H30C15O2"
data = { tag123 = 132906.363, dag1223 = 0.0, mag2 = 0.0 }
[[fatty_acids]]
label = "Hexadecanoic acid, methyl ester"
formula = "H30C15O2"
data = { tag123 = 11274419.872, dag1223 = 1206585.242, mag2 = 160056.901 }
[[fatty_acids]]
label = "7-Hexadecenoic acid, methyl ester, (Z)"
formula = "H30C15O2"
data = { tag123 = 539840.431, dag1223 = 17064.358, mag2 = 0.0 }
[[fatty_acids]]
label = "9-Hexadecenoic acid, methyl ester, (Z)"
formula = "H30C15O2"
data = { tag123 = 118753.632, dag1223 = 0.0, mag2 = 0.0 }
[[fatty_acids]]
label = "Methyl stearate"
formula = "H30C15O2"
data = { tag123 = 578215.174, dag1223 = 354063.374, mag2 = 0.0 }
[[fatty_acids]]
label = "7,10,13-Hexadecatrienoic acid (ZZZ)"
formula = "H30C15O2"
data = { tag123 = 141611.249, dag1223 = 0.0, mag2 = 0.0 }
[[fatty_acids]]
label = "9-Octadecenoic acid, methyl ester"
formula = "H30C15O2"
data = { tag123 = 153164714.095, dag1223 = 10433836.352, mag2 = 5523348.106 }
[[fatty_acids]]
label = "11-Octadecenoic acid, methyl ester"
formula = "H30C15O2"
data = { tag123 = 3217637.386, dag1223 = 111315.052, mag2 = 0.0 }
[[fatty_acids]]
label = "9,12-Octadecadienoic acid, methyl ester"
formula = "H30C15O2"
data = { tag123 = 105565236.047, dag1223 = 7289965.310, mag2 = 3938684.811 }
[[fatty_acids]]
label = "Eicosanoic acid, methyl ester"
formula = "H30C15O2"
data = { tag123 = 329851.648, dag1223 = 0.0, mag2 = 0.0 }
[[fatty_acids]]
label = "9,12,15-Octadecatrienoic acid, methyl ester, (Z.Z.Z)"
formula = "H30C15O2"
data = { tag123 = 13990826.565, dag1223 = 1126897.687, mag2 = 614974.569 }
[[fatty_acids]]
label = "cis-Methyl 11-eicosenoate"
formula = "H30C15O2"
data = { tag123 = 79506670.523, dag1223 = 2307124.554, mag2 = 0.0 }
[[fatty_acids]]
label = "cis-13-Eicosenoic acid, methyl ester"
formula = "H30C15O2"
data = { tag123 = 1170415.213, dag1223 = 0.0, mag2 = 0.0 }
[[fatty_acids]]
label = "11,14-Eicosadienoic acid, methyl ester"
formula = "H30C15O2"
data = { tag123 = 1217501.691, dag1223 = 24518.061, mag2 = 0.0 }
[[fatty_acids]]
label = "13-Docosenoic acid, methyl ester"
formula = "H30C15O2"
data = { tag123 = 399938020.170, dag1223 = 39030.157, mag2 = 0.0 }
[[fatty_acids]]
label = "Methyl 11-docosenoate"
formula = "H30C15O2"
data = { tag123 = 3336463.905, dag1223 = 8925117.791, mag2 = 0.0 }
[[fatty_acids]]
label = "cis-13,16-Docasadienoic acid"
formula = "H30C15O2"
data = { tag123 = 1804511.634, dag1223 = 20439.132, mag2 = 0.0 }
[[fatty_acids]]
label = "15-Tetracosenoic acid, methyl ester"
formula = "H30C15O2"
data = { tag123 = 56883069.216, dag1223 = 1217751.984, mag2 = 0.0 }
[[fatty_acids]]
label = "11,14-Eicosadienoic acid, methyl ester"
formula = "H30C15O2"
data = { tag123 = 226972.494, dag1223 = 0.0, mag2 = 0.0 }
