name: Github Pages

on:
  workflow_run:
    branches: [main]
    workflows: [Rust]
    types: [completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        target: wasm32-unknown-unknown
        default: true
        override: true
    - uses: Swatinem/rust-cache@v2
    - uses: jetli/trunk-action@v0.4.0
    - uses: jetli/wasm-bindgen-action@v0.2.0
    - name: build
      # "${GITHUB_REPOSITORY#*/}" evaluates into the name of the repository
      # using --public-url something will allow trunk to modify all the href
      # paths like from favicon.ico to repo_name/favicon.ico . this is necessary
      # for github pages where the site is deployed to
      # username.github.io/repo_name and all files must be requested relatively
      # as eframe_template/favicon.ico. if we skip public-url option, the href
      # paths will instead request username.github.io/favicon.ico which will
      # obviously return error 404 not found.
      run: trunk build --release --public-url "${GITHUB_REPOSITORY#*/}"
    - name: write
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        single-commit: true
