name: Github Pages

on:
  workflow_run:
    branches: [main]
    workflows: [Rust]
    types: [completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        target: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
    - uses: jetli/trunk-action@v0.4.0
    - uses: jetli/wasm-bindgen-action@v0.2.0
    - name: build
      run: trunk build --release --filehash=false --public-url=${{ github.event.repository.name }}
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        clean: false
        folder: dist
        repository-name: ippras/utca
        single-commit: true
        token: ${{ secrets.deploy }}
